### PR TITLE
Fix some bugs / Fix stylesheet / Add notif position in setting

### LINKED ISSUE #33: [Bug] Ref - there are some ref issue (not change dynamically, etc...)

### LINKED ISSUE #34: Game - add games from game list in pinia store

### LINKED ISSUE #36: Notifier - Add Icon + Update for buy & gain

### LINKED ISSUE #37: Setting - Custom notification position

### LINKED ISSUE #38: Replace - Profile icon by User img if exist

### PR DESCRIPTION
**Pull request by DRACOX2500**

### CODE REVIEW

File: src/components/UserPage/UserPage.vue [hunk 1]
```diff
@@ -26,77 +26,80 @@ function getLevelLabelByXP(user: UserApp) {
 	const min = user.levelXpMin
 	const xp = user.xp
 	const max = user.levelXpMax
+	console.log(user)
```
Comment (Zekix27) [inline src/components/UserPage/UserPage.vue]: remove it

**Review by Zekix27 — CHANGES_REQUESTED** [review]

**Review by Zekix27 — APPROVED** [review]
